chore: autoformat yaml files

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -16,94 +16,93 @@ substitutions:
   _VC_TOKEN:
 
 steps:
+  # NOTE: This first step is an optimization. We execute CI/CD build cancel with
+  # the google provided gcloud container instead of Taito CLI, because it
+  # doesn't need to be pulled before execution -> cancel executes immediately.
+  - id: manual-cancel
+    name: "gcr.io/cloud-builders/gcloud"
+    entrypoint: "bash"
+    env:
+      - build_id=$BUILD_ID
+      - repo_name=$_REPO_NAME
+      - branch_name=$BRANCH_NAME
+    args:
+      - "-c"
+      - |
+        export taito_target_env="$${branch_name//master/prod}"
+        source ./taito-config.sh
+        echo "- Cancel all previous ongoing builds targetting the same branch"
+        gcloud builds list \
+          --format="table[no-heading](id)" \
+          --ongoing \
+          --filter=" \
+            substitutions._REPO_NAME='$${repo_name}' AND \
+            substitutions.BRANCH_NAME='$${branch_name}'" | \
+          grep -v "$${build_id}" | \
+          xargs gcloud builds cancel 2> /dev/null || :
 
-# NOTE: This first step is an optimization. We execute CI/CD build cancel with
-# the google provided gcloud container instead of Taito CLI, because it
-# doesn't need to be pulled before execution -> cancel executes immediately.
-- id: manual-cancel
-  name: 'gcr.io/cloud-builders/gcloud'
-  entrypoint: 'bash'
-  env:
-    - build_id=$BUILD_ID
-    - repo_name=$_REPO_NAME
-    - branch_name=$BRANCH_NAME
-  args:
-  - '-c'
-  - |
-    export taito_target_env="$${branch_name//master/prod}"
-    source ./taito-config.sh
-    echo "- Cancel all previous ongoing builds targetting the same branch"
-    gcloud builds list \
-      --format="table[no-heading](id)" \
-      --ongoing \
-      --filter=" \
-        substitutions._REPO_NAME='$${repo_name}' AND \
-        substitutions.BRANCH_NAME='$${branch_name}'" | \
-      grep -v "$${build_id}" | \
-      xargs gcloud builds cancel 2> /dev/null || :
+  # ----------------------- Taito CLI ----------------------------------
 
-# ----------------------- Taito CLI ----------------------------------
+  # Prepare build
 
-# Prepare build
+  - id: build-prepare
+    waitFor: ["-"]
+    name: "${_TEMPLATE_DEFAULT_TAITO_IMAGE}"
+    args: ["build-prepare:$BRANCH_NAME", "$COMMIT_SHA"]
+    env:
+      - taito_mode=ci
+      - taito_ci_phases=${_TAITO_CI_PHASES}
+      - VC_TOKEN=${_VC_TOKEN}
 
-- id: build-prepare
-  waitFor: ['-']
-  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
-  args: ['build-prepare:$BRANCH_NAME', '$COMMIT_SHA']
-  env:
-    - taito_mode=ci
-    - taito_ci_phases=${_TAITO_CI_PHASES}
-    - VC_TOKEN=${_VC_TOKEN}
+  # Build artifacts in parallel
 
-# Build artifacts in parallel
+  - id: artifact-prepare-wordpress
+    waitFor: ["build-prepare"]
+    name: "${_TEMPLATE_DEFAULT_TAITO_IMAGE}"
+    args: ["artifact-prepare:wordpress:$BRANCH_NAME", "$COMMIT_SHA"]
+    env:
+      - taito_mode=ci
+      - taito_ci_phases=${_TAITO_CI_PHASES}
 
-- id: artifact-prepare-wordpress
-  waitFor: ['build-prepare']
-  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
-  args: ['artifact-prepare:wordpress:$BRANCH_NAME', '$COMMIT_SHA']
-  env:
-    - taito_mode=ci
-    - taito_ci_phases=${_TAITO_CI_PHASES}
+  # Update wordpress plugins
 
-# Update wordpress plugins
+  - id: wp-plugin-update
+    name: "${_TEMPLATE_DEFAULT_TAITO_IMAGE}"
+    env:
+      - taito_mode=ci
+      - branch_name=$BRANCH_NAME
+    entrypoint: "bash"
+    args:
+      - "-c"
+      - |
+        taito wp-plugin-update:$${branch_name} || \
+          echo "WARNING: Failed updating wordpress plugins"
 
-- id: wp-plugin-update
-  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
-  env:
-    - taito_mode=ci
-    - branch_name=$BRANCH_NAME
-  entrypoint: 'bash'
-  args:
-  - '-c'
-  - |
-    taito wp-plugin-update:$${branch_name} || \
-      echo "WARNING: Failed updating wordpress plugins"
+  # Deploy to target environment
 
-# Deploy to target environment
+  - id: deployment-deploy
+    name: "${_TEMPLATE_DEFAULT_TAITO_IMAGE}"
+    args: ["deployment-deploy:$BRANCH_NAME", "$COMMIT_SHA"]
+    env:
+      - taito_mode=ci
+      - taito_ci_phases=${_TAITO_CI_PHASES}
 
-- id: deployment-deploy
-  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
-  args: ['deployment-deploy:$BRANCH_NAME', '$COMMIT_SHA']
-  env:
-    - taito_mode=ci
-    - taito_ci_phases=${_TAITO_CI_PHASES}
+  # Release artifacts in parallel
 
-# Release artifacts in parallel
+  - id: artifact-release-wordpress
+    waitFor: ["deployment-deploy"]
+    name: "${_TEMPLATE_DEFAULT_TAITO_IMAGE}"
+    args: ["artifact-release:wordpress:$BRANCH_NAME", "$COMMIT_SHA"]
+    env:
+      - taito_mode=ci
+      - taito_ci_phases=${_TAITO_CI_PHASES}
 
-- id: artifact-release-wordpress
-  waitFor: ['deployment-deploy']
-  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
-  args: ['artifact-release:wordpress:$BRANCH_NAME', '$COMMIT_SHA']
-  env:
-    - taito_mode=ci
-    - taito_ci_phases=${_TAITO_CI_PHASES}
+  # Release build
 
-# Release build
-
-- id: build-release
-  name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
-  args: ['build-release:$BRANCH_NAME']
-  env:
-    - taito_mode=ci
-    - taito_ci_phases=${_TAITO_CI_PHASES}
-    - VC_TOKEN=${_VC_TOKEN}
+  - id: build-release
+    name: "${_TEMPLATE_DEFAULT_TAITO_IMAGE}"
+    args: ["build-release:$BRANCH_NAME"]
+    env:
+      - taito_mode=ci
+      - taito_ci_phases=${_TAITO_CI_PHASES}
+      - VC_TOKEN=${_VC_TOKEN}
