chore: update taito config and helm values

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,12 +1,20 @@
 images: [
-  'eu.gcr.io/$PROJECT_ID/$REPO_NAME/wordpress:$COMMIT_SHA'
+  'eu.gcr.io/$PROJECT_ID/$_REPO_NAME/wordpress:$COMMIT_SHA'
 ]
 
 timeout: 1200s
 
+# If you want to grant outsiders access to your build logs, you mey save
+# the logs to a separate bucket and grant the outsiders access to that bucket
+# logsBucket: 'gs://my-builds' # TODO _TEMPLATE_DEFAULT for this also
+
 substitutions:
+  _REPO_NAME: wordpress-template
   _TEMPLATE_DEFAULT_TAITO_IMAGE:
   _TEMPLATE_DEFAULT_ORGANIZATION:
+  _TEMPLATE_DEFAULT_ORGANIZATION_ABBR:
+  _TEMPLATE_DEFAULT_GITHUB_ORGANIZATION:
+  _TEMPLATE_DEFAULT_SENTRY_ORGANIZATION:
   _TEMPLATE_DEFAULT_DOMAIN:
   _TEMPLATE_DEFAULT_DOMAIN_PROD:
   _TEMPLATE_DEFAULT_ZONE:
@@ -34,13 +42,16 @@ steps:
     - branch_name=$BRANCH_NAME
     - commit_sha=$COMMIT_SHA
     - build_id=$BUILD_ID
-    - full_repo_name=$REPO_NAME
-    - image_path=eu.gcr.io/$PROJECT_ID/$REPO_NAME/wordpress:$COMMIT_SHA
+    - full_repo_name=$_REPO_NAME
+    - image_path=eu.gcr.io/$PROJECT_ID/$_REPO_NAME/wordpress:$COMMIT_SHA
   args:
   - '-c'
   - |
     export template_default_taito_image=${_TEMPLATE_DEFAULT_TAITO_IMAGE}
     export template_default_organization=${_TEMPLATE_DEFAULT_ORGANIZATION}
+    export template_default_organization_abbr=${_TEMPLATE_DEFAULT_ORGANIZATION_ABBR}
+    export template_default_github_organization=${_TEMPLATE_DEFAULT_GITHUB_ORGANIZATION}
+    export template_default_sentry_organization=${_TEMPLATE_DEFAULT_SENTRY_ORGANIZATION}
     export template_default_domain=${_TEMPLATE_DEFAULT_DOMAIN}
     export template_default_domain_prod=${_TEMPLATE_DEFAULT_DOMAIN_PROD}
     export template_default_zone=${_TEMPLATE_DEFAULT_ZONE}
@@ -55,32 +66,27 @@ steps:
     export template_default_registry=${_TEMPLATE_DEFAULT_REGISTRY}
     export template_default_kubernetes=${_TEMPLATE_DEFAULT_KUBERNETES}
     export template_default_mysql=${_TEMPLATE_DEFAULT_MYSQL}
-    export taito_env
-    taito_env="$${branch_name}"
-    if [[ "$${taito_env}" == "master" ]]; then
-      taito_env="prod"
+    export taito_target_env
+    taito_target_env="$${branch_name}"
+    if [[ "$${taito_target_env}" == "master" ]]; then
+      taito_target_env="prod"
     fi
+    export taito_env="$${taito_target_env}"
     source ./taito-config.sh
 
-    echo "- Get gcloud credentials"
-    gcloud container clusters get-credentials "$${kubectl_name}" \
-      --zone "$${gcloud_zone}"
-    if [[ $$? -gt 0 ]]; then
-      echo "WARNING! Get gcloud credentials failed. Build cancel not possible."
-      # exit 1
+    echo "- Get cluster credentials"
+    if ! gcloud container clusters get-credentials "$${kubectl_name}" \
+      --zone "$${gcloud_zone}"; then
+      echo "ERROR: Get cluster credentials failed"
+      exit 1
     fi
 
     echo "- Cancel all previous ongoing builds targetting the same branch"
-    # TODO just in case: filter builds that are newer than this build
-    # --> remeber to implement it also in the taito-cli cancel plugin
-    gcloud beta container builds list --ongoing | \
+    gcloud builds list --ongoing | \
       grep "$${full_repo_name}@$${branch_name}" | \
       grep -v "$${build_id}" | \
       cut -d ' ' -f 1 | \
-      xargs -L1 gcloud container builds cancel
-
-    # echo "Delete kube credentials to avoid gcloud/kubectl version mismatch"
-    # rm -rf ~/.kube
+      xargs -L1 gcloud builds cancel
 
     echo "- We ignore all fails during cancel (hence the last echo)"
 
@@ -92,11 +98,14 @@ steps:
 - id: ci-prepare
   waitFor: ['-']
   name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
-  args: ['ci-prepare:wordpress:$BRANCH_NAME', '$COMMIT_SHA', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME']
+  args: ['ci-prepare:wordpress:$BRANCH_NAME', '$COMMIT_SHA']
   env:
     - taito_mode=ci
     - template_default_taito_image=${_TEMPLATE_DEFAULT_TAITO_IMAGE}
     - template_default_organization=${_TEMPLATE_DEFAULT_ORGANIZATION}
+    - template_default_organization_abbr=${_TEMPLATE_DEFAULT_ORGANIZATION_ABBR}
+    - template_default_github_organization=${_TEMPLATE_DEFAULT_GITHUB_ORGANIZATION}
+    - template_default_sentry_organization=${_TEMPLATE_DEFAULT_SENTRY_ORGANIZATION}
     - template_default_domain=${_TEMPLATE_DEFAULT_DOMAIN}
     - template_default_domain_prod=${_TEMPLATE_DEFAULT_DOMAIN_PROD}
     - template_default_zone=${_TEMPLATE_DEFAULT_ZONE}
@@ -122,6 +131,9 @@ steps:
     - taito_mode=ci
     - template_default_taito_image=${_TEMPLATE_DEFAULT_TAITO_IMAGE}
     - template_default_organization=${_TEMPLATE_DEFAULT_ORGANIZATION}
+    - template_default_organization_abbr=${_TEMPLATE_DEFAULT_ORGANIZATION_ABBR}
+    - template_default_github_organization=${_TEMPLATE_DEFAULT_GITHUB_ORGANIZATION}
+    - template_default_sentry_organization=${_TEMPLATE_DEFAULT_SENTRY_ORGANIZATION}
     - template_default_domain=${_TEMPLATE_DEFAULT_DOMAIN}
     - template_default_domain_prod=${_TEMPLATE_DEFAULT_DOMAIN_PROD}
     - template_default_zone=${_TEMPLATE_DEFAULT_ZONE}
@@ -145,6 +157,9 @@ steps:
     - taito_mode=ci
     - template_default_taito_image=${_TEMPLATE_DEFAULT_TAITO_IMAGE}
     - template_default_organization=${_TEMPLATE_DEFAULT_ORGANIZATION}
+    - template_default_organization_abbr=${_TEMPLATE_DEFAULT_ORGANIZATION_ABBR}
+    - template_default_github_organization=${_TEMPLATE_DEFAULT_GITHUB_ORGANIZATION}
+    - template_default_sentry_organization=${_TEMPLATE_DEFAULT_SENTRY_ORGANIZATION}
     - template_default_domain=${_TEMPLATE_DEFAULT_DOMAIN}
     - template_default_domain_prod=${_TEMPLATE_DEFAULT_DOMAIN_PROD}
     - template_default_zone=${_TEMPLATE_DEFAULT_ZONE}
@@ -166,11 +181,14 @@ steps:
 - id: ci-build-wordpress
   waitFor: ['ci-release-pre']
   name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
-  args: ['ci-build:wordpress:$BRANCH_NAME', '$COMMIT_SHA', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME']
+  args: ['ci-build:wordpress:$BRANCH_NAME', '$COMMIT_SHA']
   env:
     - taito_mode=ci
     - template_default_taito_image=${_TEMPLATE_DEFAULT_TAITO_IMAGE}
     - template_default_organization=${_TEMPLATE_DEFAULT_ORGANIZATION}
+    - template_default_organization_abbr=${_TEMPLATE_DEFAULT_ORGANIZATION_ABBR}
+    - template_default_github_organization=${_TEMPLATE_DEFAULT_GITHUB_ORGANIZATION}
+    - template_default_sentry_organization=${_TEMPLATE_DEFAULT_SENTRY_ORGANIZATION}
     - template_default_domain=${_TEMPLATE_DEFAULT_DOMAIN}
     - template_default_domain_prod=${_TEMPLATE_DEFAULT_DOMAIN_PROD}
     - template_default_zone=${_TEMPLATE_DEFAULT_ZONE}
@@ -189,11 +207,14 @@ steps:
 - id: ci-push-wordpress
   waitFor: ['ci-build-wordpress']
   name: '${_TEMPLATE_DEFAULT_TAITO_IMAGE}'
-  args: ['ci-push:wordpress:$BRANCH_NAME', '$COMMIT_SHA', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME']
+  args: ['ci-push:wordpress:$BRANCH_NAME', '$COMMIT_SHA']
   env:
     - taito_mode=ci
     - template_default_taito_image=${_TEMPLATE_DEFAULT_TAITO_IMAGE}
     - template_default_organization=${_TEMPLATE_DEFAULT_ORGANIZATION}
+    - template_default_organization_abbr=${_TEMPLATE_DEFAULT_ORGANIZATION_ABBR}
+    - template_default_github_organization=${_TEMPLATE_DEFAULT_GITHUB_ORGANIZATION}
+    - template_default_sentry_organization=${_TEMPLATE_DEFAULT_SENTRY_ORGANIZATION}
     - template_default_domain=${_TEMPLATE_DEFAULT_DOMAIN}
     - template_default_domain_prod=${_TEMPLATE_DEFAULT_DOMAIN_PROD}
     - template_default_zone=${_TEMPLATE_DEFAULT_ZONE}
@@ -218,6 +239,9 @@ steps:
     - branch_name=$BRANCH_NAME
     - template_default_taito_image=${_TEMPLATE_DEFAULT_TAITO_IMAGE}
     - template_default_organization=${_TEMPLATE_DEFAULT_ORGANIZATION}
+    - template_default_organization_abbr=${_TEMPLATE_DEFAULT_ORGANIZATION_ABBR}
+    - template_default_github_organization=${_TEMPLATE_DEFAULT_GITHUB_ORGANIZATION}
+    - template_default_sentry_organization=${_TEMPLATE_DEFAULT_SENTRY_ORGANIZATION}
     - template_default_domain=${_TEMPLATE_DEFAULT_DOMAIN}
     - template_default_domain_prod=${_TEMPLATE_DEFAULT_DOMAIN_PROD}
     - template_default_zone=${_TEMPLATE_DEFAULT_ZONE}
@@ -248,6 +272,9 @@ steps:
     - taito_mode=ci
     - template_default_taito_image=${_TEMPLATE_DEFAULT_TAITO_IMAGE}
     - template_default_organization=${_TEMPLATE_DEFAULT_ORGANIZATION}
+    - template_default_organization_abbr=${_TEMPLATE_DEFAULT_ORGANIZATION_ABBR}
+    - template_default_github_organization=${_TEMPLATE_DEFAULT_GITHUB_ORGANIZATION}
+    - template_default_sentry_organization=${_TEMPLATE_DEFAULT_SENTRY_ORGANIZATION}
     - template_default_domain=${_TEMPLATE_DEFAULT_DOMAIN}
     - template_default_domain_prod=${_TEMPLATE_DEFAULT_DOMAIN_PROD}
     - template_default_zone=${_TEMPLATE_DEFAULT_ZONE}
@@ -272,6 +299,9 @@ steps:
     - taito_mode=ci
     - template_default_taito_image=${_TEMPLATE_DEFAULT_TAITO_IMAGE}
     - template_default_organization=${_TEMPLATE_DEFAULT_ORGANIZATION}
+    - template_default_organization_abbr=${_TEMPLATE_DEFAULT_ORGANIZATION_ABBR}
+    - template_default_github_organization=${_TEMPLATE_DEFAULT_GITHUB_ORGANIZATION}
+    - template_default_sentry_organization=${_TEMPLATE_DEFAULT_SENTRY_ORGANIZATION}
     - template_default_domain=${_TEMPLATE_DEFAULT_DOMAIN}
     - template_default_domain_prod=${_TEMPLATE_DEFAULT_DOMAIN_PROD}
     - template_default_zone=${_TEMPLATE_DEFAULT_ZONE}
